# Generated by Terraform — do not edit manually
# Environment: ${environment}
# To regenerate: cd terraform/environments/${environment} && terraform apply

services:
  db:
    image: postgres:15-alpine
    container_name: ${app_name}_${environment}_db
    environment:
      POSTGRES_USER: ${db_user}
      POSTGRES_PASSWORD: ${db_password}
      POSTGRES_DB: ${db_name}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: ${app_name}_${environment}_redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: ../../../backend
    container_name: ${app_name}_${environment}_backend
    depends_on: [db, redis]
    environment:
      NODE_ENV: ${environment}
      PORT: ${backend_port}
      DATABASE_URL: postgresql://${db_user}:${db_password}@db:5432/${db_name}
      REDIS_HOST: redis
      LOG_LEVEL: ${log_level}
    ports:
      - "${backend_port}:${backend_port}"

  frontend:
    build:
      context: ../../../
    container_name: ${app_name}_${environment}_frontend
    depends_on: [backend]
    ports:
      - "${frontend_port}:80"

volumes:
  postgres_data:
