# Generated by Terraform — do not edit manually
# Environment: ${environment}

NODE_ENV=${environment}
PORT=${backend_port}
DATABASE_URL=postgresql://${db_user}:${db_password}@localhost:5432/${db_name}
LOG_LEVEL=${log_level}
RATE_LIMIT_MAX_REQUESTS=${rate_limit}
